<?php
/*
 * Generated by PEG.js 0.8.0. with php-pegjs plugin
 *
 * http://pegjs.majda.cz/
 */

namespace dice;

/* Usefull functions: */

/* chr_unicode - get unicode character from its char code */
if (!function_exists('dice\\chr_unicode')) { function chr_unicode($code) { return mb_convert_encoding('&#' . $code . ';', 'UTF-8', 'HTML-ENTITIES');} }
/* peg_regex_test - multibyte regex test */
if (!function_exists('dice\\peg_regex_test')) { function peg_regex_test($pattern, $string) { if (substr($pattern, -1) == 'i') return mb_eregi(substr($pattern, 1, -2), $string); else return mb_ereg(substr($pattern, 1, -1), $string);}}

/* Syntax error exception */
if (!class_exists("dice\\SyntaxError", false)){
class SyntaxError extends \Exception
{
    public $expected;
    public $found;
    public $grammarOffset;
    public $grammarLine;
    public $grammarColumn;
    public $name;
    public function __construct($message, $expected, $found, $offset, $line, $column)
    {
        parent::__construct($message, 0, null);
        $this->expected = $expected;
        $this->found = $found;
        $this->grammarOffset = $offset;
        $this->grammarLine = $line;
        $this->grammarColumn = $column;
        $this->name = "SyntaxError";
    }
};}

class BaseParser{


    private $peg_currPos          = 0;
    private $peg_reportedPos      = 0;
    private $peg_cachedPos        = 0;
    private $peg_cachedPosDetails = array('line' => 1, 'column' => 1, 'seenCR' => false );
    private $peg_maxFailPos       = 0;
    private $peg_maxFailExpected  = array();
    private $peg_silentFails      = 0;
    private $input                = "";


    private function cleanup_state(){
      $this->peg_currPos          = 0;
      $this->peg_reportedPos      = 0;
      $this->peg_cachedPos        = 0;
      $this->peg_cachedPosDetails = array('line' => 1, 'column' => 1, 'seenCR' => false );
      $this->peg_maxFailPos       = 0;
      $this->peg_maxFailExpected  = array();
      $this->peg_silentFails      = 0;
      $this->input                = "";

    }


    private function text() {
      return substr($this->input, $this->peg_reportedPos, $this->peg_reportedPos + $this->peg_currPos);
    }

    private function offset() {
      return $this->peg_reportedPos;
    }

    private function line() {
      $compute_pd = $this->peg_computePosDetails($this->peg_reportedPos);
      return $compute_pd["line"];
    }

    private function column() {
      $compute_pd = $this->peg_computePosDetails($this->peg_reportedPos);
      return $compute_pd["column"];
    }

    private function expected($description) {
      throw $this->peg_buildException(
        null,
        array(array("type" => "other", "description" => $description )),
        $this->peg_reportedPos
      );
    }

    private function error($message) {
      throw $this->peg_buildException($message, null, $this->peg_reportedPos);
    }

    private function peg_computePosDetails($pos) {
      $self = $this;
      $advance = function(&$details, $startPos, $endPos) use($self) {
        for ($p = $startPos; $p < $endPos; $p++) {
          $ch = mb_substr($self->input, $p, 1, "UTF-8");
          if ($ch === "\n") {
            if (!$details["seenCR"]) { $details["line"]++; }
            $details["column"] = 1;
            $details["seenCR"] = false;
          } else if ($ch === "\r" || $ch === "\u2028" || $ch === "\u2029") {
            $details["line"]++;
            $details["column"] = 1;
            $details["seenCR"] = true;
          } else {
            $details["column"]++;
            $details["seenCR"] = false;
          }
        }
      };

      if ($this->peg_cachedPos !== $pos) {
        if ($this->peg_cachedPos > $pos) {
          $this->peg_cachedPos = 0;
          $this->peg_cachedPosDetails = array( "line" => 1, "column" => 1, "seenCR" => false );
        }
        $advance($this->peg_cachedPosDetails, $this->peg_cachedPos, $pos);
        $this->peg_cachedPos = $pos;
      }

      return $this->peg_cachedPosDetails;
    }

    private function peg_fail($expected) {
      if ($this->peg_currPos < $this->peg_maxFailPos) { return; }

      if ($this->peg_currPos > $this->peg_maxFailPos) {
        $this->peg_maxFailPos = $this->peg_currPos;
        $this->peg_maxFailExpected = array();
      }

      $this->peg_maxFailExpected[] = $expected;
    }

    private function peg_buildException($message, $expected, $pos) {
      $cleanupExpected = function (&$expected){
        $i = 1;

        usort($expected, function($a, $b) {
          if ($a["description"] < $b["description"]) {
            return -1;
          } else if ($a["description"] > $b["description"]) {
            return 1;
          } else {
            return 0;
          }
        });

        while ($i < count($expected)) {
          if ($expected[$i - 1] === $expected[$i]) {
            array_splice($expected, $i, 1);
          } else {
            $i++;
          }
        }
      };

      $buildMessage = function ($expected, $found) {
        $stringEscape = function ($s) {
          $hex = function($ch) { return strtoupper(dechex(ord($ch[0])));};

            $s = str_replace("\\",   "\\\\", $s);
            $s = str_replace("\"",    "\\\"", $s);
            $s = str_replace('\x08', '\\b', $s);
            $s = str_replace('\t',   '\\t', $s);
            $s = str_replace('\n',   '\\n', $s);
            $s = str_replace('\f',   '\\f', $s);
            $s = str_replace('\r',   '\\r', $s);
            $s = preg_replace_callback('/[\\x00-\\x07\\x0B\\x0E\\x0F]/u', function($ch) use($hex) { return '\\x0' + $hex($ch[0]); }, $s);
            $s = preg_replace_callback('/[\\x10-\\x1F\\x80-\\xFF]/u',     function($ch) use($hex) { return '\\x'  + $hex($ch[0]); }, $s);
            return $s;
        };

        $expectedDescs = array_fill(0, count($expected), null);

        for ($i = 0; $i < count($expected); $i++) {
          $expectedDescs[$i] = $expected[$i]["description"];
        }

        $expectedDesc = count($expected) > 1
          ? join(", ", array_slice($expectedDescs, 0, -1))
              . " or "
              . $expectedDescs[count($expected) - 1]
          : $expectedDescs[0];

        $foundDesc = $found ? "\"" . $stringEscape($found) . "\"" : "end of input";

        return "Expected " . $expectedDesc . " but " . $foundDesc . " found.";
      };

      $posDetails = $this->peg_computePosDetails($pos);
      $found      = $pos < mb_strlen($this->input, "UTF-8") ? mb_substr($this->input, $pos, 1, "UTF-8") : null;

      if ($expected !== null) {
        $cleanupExpected($expected);
      }

      return new SyntaxError(
        $message !== null ? $message : $buildMessage($expected, $found),
        $expected,
        $found,
        $pos,
        $posDetails["line"],
        $posDetails["column"]
      );
    }

    private $peg_FAILED;
    private $peg_c0;
    private $peg_c1;
    private $peg_c2;
    private $peg_c3;
    private $peg_c4;
    private $peg_c5;
    private $peg_c6;
    private $peg_c7;
    private $peg_c8;
    private $peg_c9;
    private $peg_c10;
    private $peg_c11;
    private $peg_c12;
    private $peg_c13;
    private $peg_c14;
    private $peg_c15;
    private $peg_c16;
    private $peg_c17;
    private $peg_c18;
    private $peg_c19;
    private $peg_c20;
    private $peg_c21;
    private $peg_c22;
    private $peg_c23;
    private $peg_c24;
    private $peg_c25;
    private $peg_c26;
    private $peg_c27;
    private $peg_c28;
    private $peg_c29;
    private $peg_c30;
    private $peg_c31;
    private $peg_c32;
    private $peg_c33;
    private $peg_c34;
    private $peg_c35;
    private $peg_c36;
    private $peg_c37;
    private $peg_c38;
    private $peg_c39;
    private $peg_c40;
    private $peg_c41;
    private $peg_c42;
    private $peg_c43;
    private $peg_c44;
    private $peg_c45;
    private $peg_c46;
    private $peg_c47;
    private $peg_c48;
    private $peg_c49;
    private $peg_c50;
    private $peg_c51;
    private $peg_c52;
    private $peg_c53;
    private $peg_c54;
    private $peg_c55;

    private function peg_parsestart() {

      $s0 = $this->peg_currPos;
      $s1 = $this->peg_parseadditive();
      if ($s1 !== $this->peg_FAILED) {
        $s2 = $this->peg_parseOWS();
        if ($s2 !== $this->peg_FAILED) {
          $this->peg_reportedPos = $s0;
          $s1 = call_user_func($this->peg_c1,$s1);
          $s0 = $s1;
        } else {
          $this->peg_currPos = $s0;
          $s0 = $this->peg_c0;
        }
      } else {
        $this->peg_currPos = $s0;
        $s0 = $this->peg_c0;
      }

      return $s0;
    }

    private function peg_parseadditive() {

      $s0 = $this->peg_currPos;
      $s1 = $this->peg_parsemultiplicative();
      if ($s1 !== $this->peg_FAILED) {
        $s2 = $this->peg_parseOWS();
        if ($s2 !== $this->peg_FAILED) {
          if (peg_regex_test($this->peg_c2, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
            $s3 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
            $this->peg_currPos++;
          } else {
            $s3 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c3); }
          }
          if ($s3 !== $this->peg_FAILED) {
            $s4 = $this->peg_parseadditive();
            if ($s4 !== $this->peg_FAILED) {
              $this->peg_reportedPos = $s0;
              $s1 = call_user_func($this->peg_c4,$s1, $s3, $s4);
              $s0 = $s1;
            } else {
              $this->peg_currPos = $s0;
              $s0 = $this->peg_c0;
            }
          } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_c0;
          }
        } else {
          $this->peg_currPos = $s0;
          $s0 = $this->peg_c0;
        }
      } else {
        $this->peg_currPos = $s0;
        $s0 = $this->peg_c0;
      }
      if ($s0 === $this->peg_FAILED) {
        $s0 = $this->peg_parsemultiplicative();
      }

      return $s0;
    }

    private function peg_parsemultiplicative() {

      $s0 = $this->peg_currPos;
      $s1 = $this->peg_parseprimary();
      if ($s1 !== $this->peg_FAILED) {
        $s2 = $this->peg_parseOWS();
        if ($s2 !== $this->peg_FAILED) {
          if (peg_regex_test($this->peg_c5, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
            $s3 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
            $this->peg_currPos++;
          } else {
            $s3 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c6); }
          }
          if ($s3 !== $this->peg_FAILED) {
            $s4 = $this->peg_parsemultiplicative();
            if ($s4 !== $this->peg_FAILED) {
              $this->peg_reportedPos = $s0;
              $s1 = call_user_func($this->peg_c7,$s1, $s3, $s4);
              $s0 = $s1;
            } else {
              $this->peg_currPos = $s0;
              $s0 = $this->peg_c0;
            }
          } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_c0;
          }
        } else {
          $this->peg_currPos = $s0;
          $s0 = $this->peg_c0;
        }
      } else {
        $this->peg_currPos = $s0;
        $s0 = $this->peg_c0;
      }
      if ($s0 === $this->peg_FAILED) {
        $s0 = $this->peg_parseprimary();
      }

      return $s0;
    }

    private function peg_parseprimary() {

      $s0 = $this->peg_currPos;
      $s1 = $this->peg_parsenumber();
      if ($s1 !== $this->peg_FAILED) {
        $s2 = $this->peg_parseOWS();
        if ($s2 !== $this->peg_FAILED) {
          if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c8) {
            $s3 = $this->peg_c8;
            $this->peg_currPos++;
          } else {
            $s3 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c9); }
          }
          if ($s3 !== $this->peg_FAILED) {
            $s4 = $this->peg_parseadditive();
            if ($s4 !== $this->peg_FAILED) {
              $s5 = $this->peg_parseOWS();
              if ($s5 !== $this->peg_FAILED) {
                if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c10) {
                  $s6 = $this->peg_c10;
                  $this->peg_currPos++;
                } else {
                  $s6 = $this->peg_FAILED;
                  if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c11); }
                }
                if ($s6 !== $this->peg_FAILED) {
                  $this->peg_reportedPos = $s0;
                  $s1 = call_user_func($this->peg_c12,$s1, $s4);
                  $s0 = $s1;
                } else {
                  $this->peg_currPos = $s0;
                  $s0 = $this->peg_c0;
                }
              } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_c0;
              }
            } else {
              $this->peg_currPos = $s0;
              $s0 = $this->peg_c0;
            }
          } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_c0;
          }
        } else {
          $this->peg_currPos = $s0;
          $s0 = $this->peg_c0;
        }
      } else {
        $this->peg_currPos = $s0;
        $s0 = $this->peg_c0;
      }
      if ($s0 === $this->peg_FAILED) {
        $s0 = $this->peg_parsefunction();
        if ($s0 === $this->peg_FAILED) {
          $s0 = $this->peg_parsevalue();
          if ($s0 === $this->peg_FAILED) {
            $s0 = $this->peg_currPos;
            $s1 = $this->peg_parseOWS();
            if ($s1 !== $this->peg_FAILED) {
              if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c8) {
                $s2 = $this->peg_c8;
                $this->peg_currPos++;
              } else {
                $s2 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c9); }
              }
              if ($s2 !== $this->peg_FAILED) {
                $s3 = $this->peg_parseadditive();
                if ($s3 !== $this->peg_FAILED) {
                  $s4 = $this->peg_parseOWS();
                  if ($s4 !== $this->peg_FAILED) {
                    if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c10) {
                      $s5 = $this->peg_c10;
                      $this->peg_currPos++;
                    } else {
                      $s5 = $this->peg_FAILED;
                      if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c11); }
                    }
                    if ($s5 !== $this->peg_FAILED) {
                      $this->peg_reportedPos = $s0;
                      $s1 = call_user_func($this->peg_c1,$s3);
                      $s0 = $s1;
                    } else {
                      $this->peg_currPos = $s0;
                      $s0 = $this->peg_c0;
                    }
                  } else {
                    $this->peg_currPos = $s0;
                    $s0 = $this->peg_c0;
                  }
                } else {
                  $this->peg_currPos = $s0;
                  $s0 = $this->peg_c0;
                }
              } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_c0;
              }
            } else {
              $this->peg_currPos = $s0;
              $s0 = $this->peg_c0;
            }
          }
        }
      }

      return $s0;
    }

    private function peg_parsefunction() {

      $s0 = $this->peg_currPos;
      $s1 = $this->peg_parseidentifier();
      if ($s1 !== $this->peg_FAILED) {
        $s2 = $this->peg_parseOWS();
        if ($s2 !== $this->peg_FAILED) {
          if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c8) {
            $s3 = $this->peg_c8;
            $this->peg_currPos++;
          } else {
            $s3 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c9); }
          }
          if ($s3 !== $this->peg_FAILED) {
            $s4 = $this->peg_parseadditive();
            if ($s4 === $this->peg_FAILED) {
              $s4 = $this->peg_c13;
            }
            if ($s4 !== $this->peg_FAILED) {
              $s5 = $this->peg_c14;
              $s6 = $this->peg_currPos;
              $s7 = $this->peg_parseOWS();
              if ($s7 !== $this->peg_FAILED) {
                if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c15) {
                  $s8 = $this->peg_c15;
                  $this->peg_currPos++;
                } else {
                  $s8 = $this->peg_FAILED;
                  if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c16); }
                }
                if ($s8 !== $this->peg_FAILED) {
                  $s9 = $this->peg_parseadditive();
                  if ($s9 !== $this->peg_FAILED) {
                    $this->peg_reportedPos = $s6;
                    $s7 = call_user_func($this->peg_c17,$s9);
                    $s6 = $s7;
                  } else {
                    $this->peg_currPos = $s6;
                    $s6 = $this->peg_c0;
                  }
                } else {
                  $this->peg_currPos = $s6;
                  $s6 = $this->peg_c0;
                }
              } else {
                $this->peg_currPos = $s6;
                $s6 = $this->peg_c0;
              }
              while ($s6 !== $this->peg_FAILED) {
                $s5[] = $s6;
                $s6 = $this->peg_currPos;
                $s7 = $this->peg_parseOWS();
                if ($s7 !== $this->peg_FAILED) {
                  if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c15) {
                    $s8 = $this->peg_c15;
                    $this->peg_currPos++;
                  } else {
                    $s8 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c16); }
                  }
                  if ($s8 !== $this->peg_FAILED) {
                    $s9 = $this->peg_parseadditive();
                    if ($s9 !== $this->peg_FAILED) {
                      $this->peg_reportedPos = $s6;
                      $s7 = call_user_func($this->peg_c17,$s9);
                      $s6 = $s7;
                    } else {
                      $this->peg_currPos = $s6;
                      $s6 = $this->peg_c0;
                    }
                  } else {
                    $this->peg_currPos = $s6;
                    $s6 = $this->peg_c0;
                  }
                } else {
                  $this->peg_currPos = $s6;
                  $s6 = $this->peg_c0;
                }
              }
              if ($s5 !== $this->peg_FAILED) {
                $s6 = $this->peg_parseOWS();
                if ($s6 !== $this->peg_FAILED) {
                  if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c10) {
                    $s7 = $this->peg_c10;
                    $this->peg_currPos++;
                  } else {
                    $s7 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c11); }
                  }
                  if ($s7 !== $this->peg_FAILED) {
                    $this->peg_reportedPos = $s0;
                    $s1 = call_user_func($this->peg_c18,$s1, $s4, $s5);
                    $s0 = $s1;
                  } else {
                    $this->peg_currPos = $s0;
                    $s0 = $this->peg_c0;
                  }
                } else {
                  $this->peg_currPos = $s0;
                  $s0 = $this->peg_c0;
                }
              } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_c0;
              }
            } else {
              $this->peg_currPos = $s0;
              $s0 = $this->peg_c0;
            }
          } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_c0;
          }
        } else {
          $this->peg_currPos = $s0;
          $s0 = $this->peg_c0;
        }
      } else {
        $this->peg_currPos = $s0;
        $s0 = $this->peg_c0;
      }

      return $s0;
    }

    private function peg_parsevalue() {

      $s0 = $this->peg_parseroll();
      if ($s0 === $this->peg_FAILED) {
        $s0 = $this->peg_parsevariable();
        if ($s0 === $this->peg_FAILED) {
          $s0 = $this->peg_parsenumberValue();
        }
      }

      return $s0;
    }

    private function peg_parseroll() {

      $this->peg_silentFails++;
      $s0 = $this->peg_currPos;
      $s1 = $this->peg_parseinteger();
      if ($s1 === $this->peg_FAILED) {
        $s1 = $this->peg_c13;
      }
      if ($s1 !== $this->peg_FAILED) {
        $s2 = $this->peg_parseOWS();
        if ($s2 !== $this->peg_FAILED) {
          if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c20) {
            $s3 = $this->peg_c20;
            $this->peg_currPos++;
          } else {
            $s3 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c21); }
          }
          if ($s3 !== $this->peg_FAILED) {
            $s4 = $this->peg_parseinteger();
            if ($s4 !== $this->peg_FAILED) {
              $this->peg_reportedPos = $s0;
              $s1 = call_user_func($this->peg_c22,$s1, $s4);
              $s0 = $s1;
            } else {
              $this->peg_currPos = $s0;
              $s0 = $this->peg_c0;
            }
          } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_c0;
          }
        } else {
          $this->peg_currPos = $s0;
          $s0 = $this->peg_c0;
        }
      } else {
        $this->peg_currPos = $s0;
        $s0 = $this->peg_c0;
      }
      $this->peg_silentFails--;
      if ($s0 === $this->peg_FAILED) {
        $s1 = $this->peg_FAILED;
        if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c19); }
      }

      return $s0;
    }

    private function peg_parsevariable() {

      $s0 = $this->peg_currPos;
      $s1 = $this->peg_parseidentifier();
      if ($s1 !== $this->peg_FAILED) {
        $this->peg_reportedPos = $s0;
        $s1 = call_user_func($this->peg_c23,$s1);
      }
      $s0 = $s1;

      return $s0;
    }

    private function peg_parsenumberValue() {

      $this->peg_silentFails++;
      $s0 = $this->peg_currPos;
      $s1 = $this->peg_parsenumber();
      if ($s1 !== $this->peg_FAILED) {
        $this->peg_reportedPos = $s0;
        $s1 = call_user_func($this->peg_c25,$s1);
      }
      $s0 = $s1;
      $this->peg_silentFails--;
      if ($s0 === $this->peg_FAILED) {
        $s1 = $this->peg_FAILED;
        if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c24); }
      }

      return $s0;
    }

    private function peg_parsenumber() {

      $this->peg_silentFails++;
      $s0 = $this->peg_currPos;
      $s1 = $this->peg_parseOWS();
      if ($s1 !== $this->peg_FAILED) {
        $s2 = $this->peg_currPos;
        $s3 = $this->peg_currPos;
        $s4 = $this->peg_c14;
        if (peg_regex_test($this->peg_c27, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
          $s5 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
          $this->peg_currPos++;
        } else {
          $s5 = $this->peg_FAILED;
          if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c28); }
        }
        if ($s5 !== $this->peg_FAILED) {
          while ($s5 !== $this->peg_FAILED) {
            $s4[] = $s5;
            if (peg_regex_test($this->peg_c27, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
              $s5 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
              $this->peg_currPos++;
            } else {
              $s5 = $this->peg_FAILED;
              if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c28); }
            }
          }
        } else {
          $s4 = $this->peg_c0;
        }
        if ($s4 !== $this->peg_FAILED) {
          $s5 = $this->peg_currPos;
          if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c29) {
            $s6 = $this->peg_c29;
            $this->peg_currPos++;
          } else {
            $s6 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c30); }
          }
          if ($s6 !== $this->peg_FAILED) {
            $s7 = $this->peg_c14;
            if (peg_regex_test($this->peg_c27, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
              $s8 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
              $this->peg_currPos++;
            } else {
              $s8 = $this->peg_FAILED;
              if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c28); }
            }
            while ($s8 !== $this->peg_FAILED) {
              $s7[] = $s8;
              if (peg_regex_test($this->peg_c27, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                $s8 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                $this->peg_currPos++;
              } else {
                $s8 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c28); }
              }
            }
            if ($s7 !== $this->peg_FAILED) {
              $s6 = array($s6, $s7);
              $s5 = $s6;
            } else {
              $this->peg_currPos = $s5;
              $s5 = $this->peg_c0;
            }
          } else {
            $this->peg_currPos = $s5;
            $s5 = $this->peg_c0;
          }
          if ($s5 === $this->peg_FAILED) {
            $s5 = $this->peg_c13;
          }
          if ($s5 !== $this->peg_FAILED) {
            $s4 = array($s4, $s5);
            $s3 = $s4;
          } else {
            $this->peg_currPos = $s3;
            $s3 = $this->peg_c0;
          }
        } else {
          $this->peg_currPos = $s3;
          $s3 = $this->peg_c0;
        }
        if ($s3 === $this->peg_FAILED) {
          $s3 = $this->peg_currPos;
          if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c29) {
            $s4 = $this->peg_c29;
            $this->peg_currPos++;
          } else {
            $s4 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c30); }
          }
          if ($s4 !== $this->peg_FAILED) {
            $s5 = $this->peg_c14;
            if (peg_regex_test($this->peg_c27, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
              $s6 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
              $this->peg_currPos++;
            } else {
              $s6 = $this->peg_FAILED;
              if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c28); }
            }
            if ($s6 !== $this->peg_FAILED) {
              while ($s6 !== $this->peg_FAILED) {
                $s5[] = $s6;
                if (peg_regex_test($this->peg_c27, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                  $s6 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                  $this->peg_currPos++;
                } else {
                  $s6 = $this->peg_FAILED;
                  if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c28); }
                }
              }
            } else {
              $s5 = $this->peg_c0;
            }
            if ($s5 !== $this->peg_FAILED) {
              $s4 = array($s4, $s5);
              $s3 = $s4;
            } else {
              $this->peg_currPos = $s3;
              $s3 = $this->peg_c0;
            }
          } else {
            $this->peg_currPos = $s3;
            $s3 = $this->peg_c0;
          }
        }
        if ($s3 !== $this->peg_FAILED) {
          $s3 = mb_substr($this->input, $s2, $this->peg_currPos - $s2, "UTF-8");
        }
        $s2 = $s3;
        if ($s2 !== $this->peg_FAILED) {
          $this->peg_reportedPos = $s0;
          $s1 = call_user_func($this->peg_c31,$s2);
          $s0 = $s1;
        } else {
          $this->peg_currPos = $s0;
          $s0 = $this->peg_c0;
        }
      } else {
        $this->peg_currPos = $s0;
        $s0 = $this->peg_c0;
      }
      $this->peg_silentFails--;
      if ($s0 === $this->peg_FAILED) {
        $s1 = $this->peg_FAILED;
        if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c26); }
      }

      return $s0;
    }

    private function peg_parseinteger() {

      $this->peg_silentFails++;
      $s0 = $this->peg_currPos;
      $s1 = $this->peg_parseOWS();
      if ($s1 !== $this->peg_FAILED) {
        $s2 = $this->peg_currPos;
        $s3 = $this->peg_c14;
        if (peg_regex_test($this->peg_c27, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
          $s4 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
          $this->peg_currPos++;
        } else {
          $s4 = $this->peg_FAILED;
          if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c28); }
        }
        if ($s4 !== $this->peg_FAILED) {
          while ($s4 !== $this->peg_FAILED) {
            $s3[] = $s4;
            if (peg_regex_test($this->peg_c27, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
              $s4 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
              $this->peg_currPos++;
            } else {
              $s4 = $this->peg_FAILED;
              if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c28); }
            }
          }
        } else {
          $s3 = $this->peg_c0;
        }
        if ($s3 !== $this->peg_FAILED) {
          $s3 = mb_substr($this->input, $s2, $this->peg_currPos - $s2, "UTF-8");
        }
        $s2 = $s3;
        if ($s2 !== $this->peg_FAILED) {
          $this->peg_reportedPos = $s0;
          $s1 = call_user_func($this->peg_c33,$s2);
          $s0 = $s1;
        } else {
          $this->peg_currPos = $s0;
          $s0 = $this->peg_c0;
        }
      } else {
        $this->peg_currPos = $s0;
        $s0 = $this->peg_c0;
      }
      $this->peg_silentFails--;
      if ($s0 === $this->peg_FAILED) {
        $s1 = $this->peg_FAILED;
        if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c32); }
      }

      return $s0;
    }

    private function peg_parseidentifier() {

      $this->peg_silentFails++;
      $s0 = $this->peg_currPos;
      $s1 = $this->peg_parseOWS();
      if ($s1 !== $this->peg_FAILED) {
        $s2 = $this->peg_currPos;
        $s3 = $this->peg_currPos;
        if (peg_regex_test($this->peg_c35, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
          $s4 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
          $this->peg_currPos++;
        } else {
          $s4 = $this->peg_FAILED;
          if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c36); }
        }
        if ($s4 !== $this->peg_FAILED) {
          $s5 = $this->peg_c14;
          if (peg_regex_test($this->peg_c37, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
            $s6 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
            $this->peg_currPos++;
          } else {
            $s6 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c38); }
          }
          if ($s6 !== $this->peg_FAILED) {
            while ($s6 !== $this->peg_FAILED) {
              $s5[] = $s6;
              if (peg_regex_test($this->peg_c37, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                $s6 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                $this->peg_currPos++;
              } else {
                $s6 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c38); }
              }
            }
          } else {
            $s5 = $this->peg_c0;
          }
          if ($s5 !== $this->peg_FAILED) {
            $s4 = array($s4, $s5);
            $s3 = $s4;
          } else {
            $this->peg_currPos = $s3;
            $s3 = $this->peg_c0;
          }
        } else {
          $this->peg_currPos = $s3;
          $s3 = $this->peg_c0;
        }
        if ($s3 !== $this->peg_FAILED) {
          $s3 = mb_substr($this->input, $s2, $this->peg_currPos - $s2, "UTF-8");
        }
        $s2 = $s3;
        if ($s2 !== $this->peg_FAILED) {
          $this->peg_reportedPos = $s0;
          $s1 = call_user_func($this->peg_c39,$s2);
          $s0 = $s1;
        } else {
          $this->peg_currPos = $s0;
          $s0 = $this->peg_c0;
        }
      } else {
        $this->peg_currPos = $s0;
        $s0 = $this->peg_c0;
      }
      if ($s0 === $this->peg_FAILED) {
        $s0 = $this->peg_currPos;
        $s1 = $this->peg_parseOWS();
        if ($s1 !== $this->peg_FAILED) {
          if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c40) {
            $s2 = $this->peg_c40;
            $this->peg_currPos++;
          } else {
            $s2 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c41); }
          }
          if ($s2 !== $this->peg_FAILED) {
            $s3 = $this->peg_currPos;
            $s4 = $this->peg_currPos;
            $s5 = $this->peg_c14;
            if (peg_regex_test($this->peg_c42, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
              $s6 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
              $this->peg_currPos++;
            } else {
              $s6 = $this->peg_FAILED;
              if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c43); }
            }
            while ($s6 !== $this->peg_FAILED) {
              $s5[] = $s6;
              if (peg_regex_test($this->peg_c42, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                $s6 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                $this->peg_currPos++;
              } else {
                $s6 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c43); }
              }
            }
            if ($s5 !== $this->peg_FAILED) {
              $s6 = $this->peg_c14;
              $s7 = $this->peg_currPos;
              if (mb_substr($this->input, $this->peg_currPos, 2, "UTF-8") === $this->peg_c44) {
                $s8 = $this->peg_c44;
                $this->peg_currPos += 2;
              } else {
                $s8 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c45); }
              }
              if ($s8 !== $this->peg_FAILED) {
                $s9 = $this->peg_c14;
                if (peg_regex_test($this->peg_c42, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                  $s10 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                  $this->peg_currPos++;
                } else {
                  $s10 = $this->peg_FAILED;
                  if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c43); }
                }
                if ($s10 !== $this->peg_FAILED) {
                  while ($s10 !== $this->peg_FAILED) {
                    $s9[] = $s10;
                    if (peg_regex_test($this->peg_c42, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                      $s10 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                      $this->peg_currPos++;
                    } else {
                      $s10 = $this->peg_FAILED;
                      if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c43); }
                    }
                  }
                } else {
                  $s9 = $this->peg_c0;
                }
                if ($s9 !== $this->peg_FAILED) {
                  $s8 = array($s8, $s9);
                  $s7 = $s8;
                } else {
                  $this->peg_currPos = $s7;
                  $s7 = $this->peg_c0;
                }
              } else {
                $this->peg_currPos = $s7;
                $s7 = $this->peg_c0;
              }
              while ($s7 !== $this->peg_FAILED) {
                $s6[] = $s7;
                $s7 = $this->peg_currPos;
                if (mb_substr($this->input, $this->peg_currPos, 2, "UTF-8") === $this->peg_c44) {
                  $s8 = $this->peg_c44;
                  $this->peg_currPos += 2;
                } else {
                  $s8 = $this->peg_FAILED;
                  if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c45); }
                }
                if ($s8 !== $this->peg_FAILED) {
                  $s9 = $this->peg_c14;
                  if (peg_regex_test($this->peg_c42, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                    $s10 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                    $this->peg_currPos++;
                  } else {
                    $s10 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c43); }
                  }
                  if ($s10 !== $this->peg_FAILED) {
                    while ($s10 !== $this->peg_FAILED) {
                      $s9[] = $s10;
                      if (peg_regex_test($this->peg_c42, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                        $s10 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                        $this->peg_currPos++;
                      } else {
                        $s10 = $this->peg_FAILED;
                        if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c43); }
                      }
                    }
                  } else {
                    $s9 = $this->peg_c0;
                  }
                  if ($s9 !== $this->peg_FAILED) {
                    $s8 = array($s8, $s9);
                    $s7 = $s8;
                  } else {
                    $this->peg_currPos = $s7;
                    $s7 = $this->peg_c0;
                  }
                } else {
                  $this->peg_currPos = $s7;
                  $s7 = $this->peg_c0;
                }
              }
              if ($s6 !== $this->peg_FAILED) {
                $s5 = array($s5, $s6);
                $s4 = $s5;
              } else {
                $this->peg_currPos = $s4;
                $s4 = $this->peg_c0;
              }
            } else {
              $this->peg_currPos = $s4;
              $s4 = $this->peg_c0;
            }
            if ($s4 !== $this->peg_FAILED) {
              $s4 = mb_substr($this->input, $s3, $this->peg_currPos - $s3, "UTF-8");
            }
            $s3 = $s4;
            if ($s3 !== $this->peg_FAILED) {
              if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c40) {
                $s4 = $this->peg_c40;
                $this->peg_currPos++;
              } else {
                $s4 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c41); }
              }
              if ($s4 !== $this->peg_FAILED) {
                $this->peg_reportedPos = $s0;
                $s1 = call_user_func($this->peg_c39,$s3);
                $s0 = $s1;
              } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_c0;
              }
            } else {
              $this->peg_currPos = $s0;
              $s0 = $this->peg_c0;
            }
          } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_c0;
          }
        } else {
          $this->peg_currPos = $s0;
          $s0 = $this->peg_c0;
        }
        if ($s0 === $this->peg_FAILED) {
          $s0 = $this->peg_currPos;
          $s1 = $this->peg_parseOWS();
          if ($s1 !== $this->peg_FAILED) {
            if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c46) {
              $s2 = $this->peg_c46;
              $this->peg_currPos++;
            } else {
              $s2 = $this->peg_FAILED;
              if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c47); }
            }
            if ($s2 !== $this->peg_FAILED) {
              $s3 = $this->peg_currPos;
              $s4 = $this->peg_currPos;
              $s5 = $this->peg_c14;
              if (peg_regex_test($this->peg_c48, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                $s6 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                $this->peg_currPos++;
              } else {
                $s6 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c49); }
              }
              while ($s6 !== $this->peg_FAILED) {
                $s5[] = $s6;
                if (peg_regex_test($this->peg_c48, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                  $s6 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                  $this->peg_currPos++;
                } else {
                  $s6 = $this->peg_FAILED;
                  if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c49); }
                }
              }
              if ($s5 !== $this->peg_FAILED) {
                $s6 = $this->peg_c14;
                $s7 = $this->peg_currPos;
                if (mb_substr($this->input, $this->peg_currPos, 2, "UTF-8") === $this->peg_c50) {
                  $s8 = $this->peg_c50;
                  $this->peg_currPos += 2;
                } else {
                  $s8 = $this->peg_FAILED;
                  if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c51); }
                }
                if ($s8 !== $this->peg_FAILED) {
                  $s9 = $this->peg_c14;
                  if (peg_regex_test($this->peg_c48, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                    $s10 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                    $this->peg_currPos++;
                  } else {
                    $s10 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c49); }
                  }
                  if ($s10 !== $this->peg_FAILED) {
                    while ($s10 !== $this->peg_FAILED) {
                      $s9[] = $s10;
                      if (peg_regex_test($this->peg_c48, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                        $s10 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                        $this->peg_currPos++;
                      } else {
                        $s10 = $this->peg_FAILED;
                        if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c49); }
                      }
                    }
                  } else {
                    $s9 = $this->peg_c0;
                  }
                  if ($s9 !== $this->peg_FAILED) {
                    $s8 = array($s8, $s9);
                    $s7 = $s8;
                  } else {
                    $this->peg_currPos = $s7;
                    $s7 = $this->peg_c0;
                  }
                } else {
                  $this->peg_currPos = $s7;
                  $s7 = $this->peg_c0;
                }
                while ($s7 !== $this->peg_FAILED) {
                  $s6[] = $s7;
                  $s7 = $this->peg_currPos;
                  if (mb_substr($this->input, $this->peg_currPos, 2, "UTF-8") === $this->peg_c50) {
                    $s8 = $this->peg_c50;
                    $this->peg_currPos += 2;
                  } else {
                    $s8 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c51); }
                  }
                  if ($s8 !== $this->peg_FAILED) {
                    $s9 = $this->peg_c14;
                    if (peg_regex_test($this->peg_c48, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                      $s10 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                      $this->peg_currPos++;
                    } else {
                      $s10 = $this->peg_FAILED;
                      if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c49); }
                    }
                    if ($s10 !== $this->peg_FAILED) {
                      while ($s10 !== $this->peg_FAILED) {
                        $s9[] = $s10;
                        if (peg_regex_test($this->peg_c48, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
                          $s10 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
                          $this->peg_currPos++;
                        } else {
                          $s10 = $this->peg_FAILED;
                          if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c49); }
                        }
                      }
                    } else {
                      $s9 = $this->peg_c0;
                    }
                    if ($s9 !== $this->peg_FAILED) {
                      $s8 = array($s8, $s9);
                      $s7 = $s8;
                    } else {
                      $this->peg_currPos = $s7;
                      $s7 = $this->peg_c0;
                    }
                  } else {
                    $this->peg_currPos = $s7;
                    $s7 = $this->peg_c0;
                  }
                }
                if ($s6 !== $this->peg_FAILED) {
                  $s5 = array($s5, $s6);
                  $s4 = $s5;
                } else {
                  $this->peg_currPos = $s4;
                  $s4 = $this->peg_c0;
                }
              } else {
                $this->peg_currPos = $s4;
                $s4 = $this->peg_c0;
              }
              if ($s4 !== $this->peg_FAILED) {
                $s4 = mb_substr($this->input, $s3, $this->peg_currPos - $s3, "UTF-8");
              }
              $s3 = $s4;
              if ($s3 !== $this->peg_FAILED) {
                if (mb_substr($this->input, $this->peg_currPos, 1, "UTF-8") === $this->peg_c52) {
                  $s4 = $this->peg_c52;
                  $this->peg_currPos++;
                } else {
                  $s4 = $this->peg_FAILED;
                  if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c53); }
                }
                if ($s4 !== $this->peg_FAILED) {
                  $this->peg_reportedPos = $s0;
                  $s1 = call_user_func($this->peg_c39,$s3);
                  $s0 = $s1;
                } else {
                  $this->peg_currPos = $s0;
                  $s0 = $this->peg_c0;
                }
              } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_c0;
              }
            } else {
              $this->peg_currPos = $s0;
              $s0 = $this->peg_c0;
            }
          } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_c0;
          }
        }
      }
      $this->peg_silentFails--;
      if ($s0 === $this->peg_FAILED) {
        $s1 = $this->peg_FAILED;
        if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c34); }
      }

      return $s0;
    }

    private function peg_parseOWS() {

      $s0 = $this->peg_c14;
      if (peg_regex_test($this->peg_c54, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
        $s1 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
        $this->peg_currPos++;
      } else {
        $s1 = $this->peg_FAILED;
        if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c55); }
      }
      while ($s1 !== $this->peg_FAILED) {
        $s0[] = $s1;
        if (peg_regex_test($this->peg_c54, mb_substr($this->input, $this->peg_currPos, 1, "UTF-8"))) {
          $s1 = mb_substr($this->input, $this->peg_currPos, 1, "UTF-8");
          $this->peg_currPos++;
        } else {
          $s1 = $this->peg_FAILED;
          if ($this->peg_silentFails === 0) { $this->peg_fail($this->peg_c55); }
        }
      }

      return $s0;
    }

  public function parse($input) {
    $arguments = func_get_args();
    $options = count($arguments) > 1 ? $arguments[1] : array();
    $this->cleanup_state();
    $this->input = $input;
    $old_regex_encoding = mb_regex_encoding();
    mb_regex_encoding("UTF-8");

    $this->peg_FAILED = new \stdClass;
    $this->peg_c0 = $this->peg_FAILED;
    $this->peg_c1 = function($additive) { return $additive; };
    $this->peg_c2 = "/^[+-]/";
    $this->peg_c3 = array( "type" => "class", "value" => "[+\\-]", "description" => "[+\\-]" );
    $this->peg_c4 = function($left,$oper,$right) { return new Operation(($oper == '+') ? 'add' : 'subtract', $left, $right); };
    $this->peg_c5 = "/^[*\\/]/";
    $this->peg_c6 = array( "type" => "class", "value" => "[*\\/]", "description" => "[*\\/]" );
    $this->peg_c7 = function($left,$oper,$right) { return new Operation(($oper == '*') ? 'multiply' : 'divide', $left, $right); };
    $this->peg_c8 = "(";
    $this->peg_c9 = array( "type" => "literal", "value" => "(", "description" => "\"(\"" );
    $this->peg_c10 = ")";
    $this->peg_c11 = array( "type" => "literal", "value" => ")", "description" => "\")\"" );
    $this->peg_c12 = function($count,$additive) { return new Repeat($count, $additive); };
    $this->peg_c13 = null;
    $this->peg_c14 = array();
    $this->peg_c15 = ",";
    $this->peg_c16 = array( "type" => "literal", "value" => ",", "description" => "\",\"" );
    $this->peg_c17 = function($arg) { return $arg; };
    $this->peg_c18 = function($name,$arg1,$rest) { return new Func($name, array_merge([$arg1], $rest)); };
    $this->peg_c19 = array("type" => "other", "description" => "die roll" );
    $this->peg_c20 = "d";
    $this->peg_c21 = array( "type" => "literal", "value" => "d", "description" => "\"d\"" );
    $this->peg_c22 = function($count,$sides) { return new Roll($count, $sides); };
    $this->peg_c23 = function($name) { return new Variable($name); };
    $this->peg_c24 = array("type" => "other", "description" => "numeric value" );
    $this->peg_c25 = function($value) { return new Num($value); };
    $this->peg_c26 = array("type" => "other", "description" => "number" );
    $this->peg_c27 = "/^[0-9]/";
    $this->peg_c28 = array( "type" => "class", "value" => "[0-9]", "description" => "[0-9]" );
    $this->peg_c29 = ".";
    $this->peg_c30 = array( "type" => "literal", "value" => ".", "description" => "\".\"" );
    $this->peg_c31 = function($value) { return floatval($value); };
    $this->peg_c32 = array("type" => "other", "description" => "integer" );
    $this->peg_c33 = function($digits) { return intval($digits, 10); };
    $this->peg_c34 = array("type" => "other", "description" => "identifier" );
    $this->peg_c35 = "/^[A-Za-z_]/";
    $this->peg_c36 = array( "type" => "class", "value" => "[A-Za-z_]", "description" => "[A-Za-z_]" );
    $this->peg_c37 = "/^[A-Za-z0-9_]/";
    $this->peg_c38 = array( "type" => "class", "value" => "[A-Za-z0-9_]", "description" => "[A-Za-z0-9_]" );
    $this->peg_c39 = function($name) { return $name; };
    $this->peg_c40 = "'";
    $this->peg_c41 = array( "type" => "literal", "value" => "'", "description" => "\"'\"" );
    $this->peg_c42 = "/^[^']/";
    $this->peg_c43 = array( "type" => "class", "value" => "[^']", "description" => "[^']" );
    $this->peg_c44 = "''";
    $this->peg_c45 = array( "type" => "literal", "value" => "''", "description" => "\"''\"" );
    $this->peg_c46 = "[";
    $this->peg_c47 = array( "type" => "literal", "value" => "[", "description" => "\"[\"" );
    $this->peg_c48 = "/^[^\\[\\]]/";
    $this->peg_c49 = array( "type" => "class", "value" => "[^[\\]]", "description" => "[^[\\]]" );
    $this->peg_c50 = "\\]";
    $this->peg_c51 = array( "type" => "literal", "value" => "\\]", "description" => "\"\\\\]\"" );
    $this->peg_c52 = "]";
    $this->peg_c53 = array( "type" => "literal", "value" => "]", "description" => "\"]\"" );
    $this->peg_c54 = "/^[ \\t\\r\\n]/";
    $this->peg_c55 = array( "type" => "class", "value" => "[ \\t\\r\\n]", "description" => "[ \\t\\r\\n]" );

    $peg_startRuleFunctions = array( 'start' => array($this, "peg_parsestart") );
    $peg_startRuleFunction  = array($this, "peg_parsestart");
    if (isset($options["startRule"])) {
      if (!(isset($peg_startRuleFunctions[$options["startRule"]]))) {
        throw new \Exception("Can't start parsing from rule \"" + $options["startRule"] + "\".");
      }

      $peg_startRuleFunction = $peg_startRuleFunctions[$options["startRule"]];
    }
    $peg_result = call_user_func($peg_startRuleFunction);

    mb_regex_encoding($old_regex_encoding);
    if ($peg_result !== $this->peg_FAILED && $this->peg_currPos === mb_strlen($input, "UTF-8")) {
      return $peg_result;
    } else {
      if ($peg_result !== $this->peg_FAILED && $this->peg_currPos < mb_strlen($input, "UTF-8")) {
        $this->peg_fail(array("type" => "end", "description" => "end of input" ));
      }

      throw $this->peg_buildException(null, $this->peg_maxFailExpected, $this->peg_maxFailPos);
    }
  }

};